### ISSUE TITLE
Can't use sum-coverage

### ISSUE THREAD

**Issue by krasnoukhov** [aktions/codeclimate-test-reporter#2]
Here's how to reproduce:

```yml
- uses: aktions/codeclimate-test-reporter@v1
  with:
    codeclimate-test-reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
    command: sum-coverage -p 2 coverage/codeclimate.*.json
```

Here's the output:

```
> Run aktions/codeclimate-test-reporter@v1
chmod +x /home/runner/work/_temp/cc-test-reporter
cc-test-reporter sum-coverage -p 2 coverage/codeclimate.*.json
Error: open ./coverage/codeclimate.*.json: no such file or directory
Usage:
  cc-test-reporter sum-coverage [flags]

Flags:
  -o, --output string   output path (default "coverage/codeclimate.json")
  -p, --parts int       total number of parts to sum

Global Flags:
  -d, --debug   run in debug mode

##[error]The process 'cc-test-reporter' failed with exit code 255
##[error]Node run failed with exit code 1
```
I guess this happens because of the way how arguments are passed into shell exec. I'm working this around:

```yml
- env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  run: cc-test-reporter sum-coverage -p 2 coverage/codeclimate.*.json
```

But this is ugly because I need to make sure to run some dummy action before so CLI tool is installed.

**Comment by alexkappa** [comment]
Hi @krasnoukhov, thanks for filing an issue. To clarify, is the issue that the file glob is not expanded?

The command attribute is split by spaces and passed down to the exec command and no other transformation takes place if I remember correctly. Any suggestions?

**Comment by krasnoukhov** [comment]
I looked deeper into this and it seems like `@actions/exec` uses `spawn` from `child_process` module. It seems like [it could work](https://stackoverflow.com/a/57467276) for our case here if `{ shell: true }` is passed as options.

Here's where options are requested:

https://github.com/actions/toolkit/blob/bfd29dcef82f324e9fb8855b6083fc0c2902bc27/packages/exec/src/toolrunner.ts#L439

And function that returns them:

https://github.com/actions/toolkit/blob/bfd29dcef82f324e9fb8855b6083fc0c2902bc27/packages/exec/src/toolrunner.ts#L372-L386

It does not seem like passing that flag would be possible. So I think our options here are:

- Propose a change to `@actions/exec` to whitelist `shell` and hope that it works
- Use `child_process.exec()` directly (might be tricky because of Windows, but it does not look like this project is tested on that platform)

**Comment by krasnoukhov** [comment]
I created #3 to use second approach. @alexkappa Let me know if that'd work

**Comment by alexkappa** [comment]
@krasnoukhov thanks for doing a deep dive on this. It's very helpful.

I think your assessment is correct, we can use `child_process.exec()` to bypass any limitations imposed by `@actions/exec`. However, I think it's worthwhile creating an issue in the actions/toolkit to ask if we can add `shell` to `ExecOptions`.

**Comment by alexkappa** [comment]
Submitted a PR to [`@actions/toolkit`](https://github.com/actions/toolkit/pull/285)

**Comment by krasnoukhov** [comment]
Thanks @alexkappa 😍
